In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
# 모든 document를 저장할 수 있는 text_set 선언
text_set = [] 

from collections import defaultdict

text_dict = defaultdict(list) # 각 text의 내용과 index를 저장하는 defaultdict

# open the folder where documents are saved, and save all the documents
path = 'data/'

for filename in os.listdir(path):
    file = open(os.path.join(path,filename), 'r', encoding='utf-8')
    text = file.readlines() # 내용을 읽는다. 
    filename_int = int(filename.replace(".txt", "")) # 파일 이름에서 .txt를 지우고 index값을 int로 바꾼다. 
    text_dict[filename_int] = text 
    #text_set.append(text)

In [3]:
text_dict.keys()

dict_keys([0, 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 4, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 5, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 6, 7, 8, 9])

In [6]:
from collections import OrderedDict

ordered_text_dict = OrderedDict(sorted(text_dict.items())) # index별로 sort한다. 

In [7]:
ordered_text_dict.keys() # 제대로 sort됬는지 본다. 

odict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [8]:
for text in ordered_text_dict: #text_set에 넣는다. 
    text_set.append(ordered_text_dict[text])

In [9]:
text_set[0][0] # 체크한다. 

' (CNN)If you remember Miley twerking or Kanye\'s mic-snatching, you\'ll know music awards can get chaotic.Like on Tuesday, when singer Taylor Swift took a Twitter dig at hip-hop queen Nicki Minaj and the Internet erupted into a sprawling conversation about race and gender. And then Kim Kardashian got involved. Stay with us.\'Black women are rarely rewarded\'It started when Minaj took to her keyboard to vent after one of her biggest hits wasn\'t nominated for video of the year for the MTV Video Music Awards.Mind you, this isn\'t any old clip. "Anaconda," an uproarious, raunchy twist on pop culture portrayals of curvy black women, received 19.6 million clicks in its first 24 hours, a music video record at the time. So the rapper had a reason to be upset when she was snubbed -- and she made her reasoning clear."If I was a different \'kind\' of artist, Anaconda would be nominated for best choreo and vid of the year as well," said Minaj."Black women influence pop culture so much but are ra

# TF-IDF Flow

- 1. 각 text별로 tokenize를 한다. 
- 2. token에서 stopwords나 필요없는 부분을 제거하고 stemming을 해준다. 
- 3. 각 document, 각 token별 token 몇개 있는지 구한 다음, table로 저장한다. 
- 4. 각 token별 어떤 document가 있는 지 inverted index를 구한다. 
- 5. tf-idf를 구한다.
- 6. query가 속한 document들만 가져온다. 
- 7. query의 tf-idf를 구한다. 
- 8. cosine-similarity를 구한다. 

# NLTK Preprocessing

### 1. 각 text별로 tokenize를 한다. 
### 2. token에서 stopwords나 필요없는 부분을 제거하고 stemming을 해준다. 

In [10]:
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem.porter import PorterStemmer
import re

In [11]:
# stopwords 불러오기.
stop = set(stopwords.words('english'))

In [12]:
# 영어 소문자만 걸러내기 위한 regex
regex = re.compile('^[a-z]*[a-z]$')

In [13]:
regex.match('president')

<re.Match object; span=(0, 9), match='president'>

In [14]:
vocab_set = set() # 모든 단어의 set
vocab_list = [] # 각 document별로 단어.
porter_stemmer = PorterStemmer() # stemmer

#for i in range(len(text_set)):
for i in range(len(text_set)):
    tokenized_temp = word_tokenize(text_set[i][0].lower()) # 소문자로 만든 뒤 tokenized를 했다. 
    split_tokenized = [] # hypen이나 .으로 연결되어 있는 token들을 포함하여 전체적인 token을 일시적으로 포함하는 list.
        
    for token in tokenized_temp:
        if '-' in token: # '-'으로 연결되어 있으면 나눠준다. 
            split_tokens = token.split('-')
            for split_token in split_tokens:
                split_tokenized.append(split_token)
        elif '.' in token: # '.'으로 연결되어 있으면 나눠준다. 
            split_tokens = token.split('.')
            for split_token in split_tokens:
                split_tokenized.append(split_token)
        else: # 해당되지 않으면 넣는다. 
            split_tokenized.append(token)
    
    
    # stopwords가 아닌것과 알파벳인것만 vocab_list에 넣는다. 
    vocab_list.append([porter_stemmer.stem(token) for token in split_tokenized if token not in stop and regex.match(token)])
    
    
    # 각 vocab을 vocab_set에 넣는다. 
    for vocab in vocab_list[i]:
        vocab_set.add(vocab)

In [15]:
tokenized_temp = word_tokenize(text_set[30][0].lower())

In [16]:
vocab_list[30]

['cnn',
 'one',
 'famou',
 'peopl',
 'us',
 'tiger',
 'wood',
 'urg',
 'compatriot',
 'unit',
 'turbul',
 'time',
 'countri',
 'arguabl',
 'recent',
 'experienc',
 'former',
 'world',
 'golfer',
 'encourag',
 'american',
 'come',
 'togeth',
 'best',
 'countri',
 'speak',
 'cnn',
 'live',
 'golf',
 'show',
 'dubaiwood',
 'talk',
 'aftermath',
 'presid',
 'trump',
 'controversi',
 'immigr',
 'ban',
 'caus',
 'ruction',
 'us',
 'throughout',
 'rest',
 'world',
 'trump',
 'order',
 'suspend',
 'us',
 'refuge',
 'system',
 'day',
 'suspend',
 'syrian',
 'refuge',
 'program',
 'indefinit',
 'ban',
 'entri',
 'seven',
 'muslim',
 'countri',
 'iran',
 'iraq',
 'libya',
 'somalia',
 'sudan',
 'syria',
 'yemen',
 'day',
 'among',
 'thing',
 'need',
 'unit',
 'american',
 'said',
 'wood',
 'play',
 'golf',
 'presid',
 'elect',
 'decemb',
 'know',
 'lot',
 'divis',
 'right',
 'time',
 'patienc',
 'uniti',
 'think',
 'win',
 'year',
 'old',
 'make',
 'second',
 'appear',
 'year',
 'dubai',
 'week',

In [17]:
len(vocab_set)

4091

In [18]:
len(vocab_list)

60

# Matrix

### 3. 각 document, 각 token별 token 몇개 있는지 구한 다음, table로 저장한다. 
### 4. 각 token별 어떤 document가 있는 지 inverted index를 구한다. 

In [19]:
from collections import defaultdict
import collections

doc_dictionary_list = [] # 각 document별 각 word별로 몇 개 있는 지를 저장하는 dictionary를 모아놓은 list

for i in range(len(vocab_list)):    
    doc_dictionary = defaultdict(int) # 각 document별로 word가 몇 개 있는 지 저장되어 있다. 

    for vocab in vocab_list[i]: # vocab_list에 단어가 몇개가 있는 지 저장 한다. 
        doc_dictionary[vocab] += 1

    for vocab in vocab_set: # 그리고 나머지는 다 0으로 채운다. 
        if doc_dictionary[vocab] != 0:
            pass
    
    od = collections.OrderedDict(sorted(doc_dictionary.items())) # keyword들을 sort한다. 
    
    doc_dictionary_list.append(od) # 마지막으로 lsit에 저장한다. 

In [20]:
inverted_index_dic = defaultdict(list) # inverted_index를 포함하는 dictionary

for vocab in vocab_set: # 만약 doc_dictionary에서 그 단어가 1이상 나오면 그 document의 index를 저장한다. 
    index = 0
    for doc_dictionary in doc_dictionary_list:
        if doc_dictionary[vocab] >= 1:
            inverted_index_dic[vocab].append(index)
    
        index += 1

In [25]:
inverted_index_dic

defaultdict(list,
            {'metaphysician': [9],
             'squad': [35],
             'explod': [31],
             'leonard': [34],
             'censor': [11],
             'bank': [6, 18, 23, 29, 44, 50],
             'bust': [10, 51],
             'forget': [18, 39, 46],
             'social': [2, 21],
             'glitch': [7],
             'russia': [41, 42, 43, 45, 46, 47, 48, 49, 50, 51],
             'stick': [4, 38],
             'citi': [9, 32, 39, 46, 48, 59],
             'bet': [34],
             'gaug': [35],
             'coachella': [13],
             'golfer': [24, 26, 27, 30, 32, 35, 39],
             'flash': [7],
             'scout': [35],
             'exclus': [20, 22, 23, 25, 29, 32, 52],
             'host': [0, 10, 17, 18, 24, 26, 27, 32, 36, 39, 56],
             'jason': [20, 22, 23, 25, 26, 29, 31, 33, 34, 35, 38],
             'crew': [3],
             'rough': [11],
             'token': [43],
             'feminist': [0],
             'check': [

In [26]:
doc_dictionary_list

[OrderedDict([('aaron', 0),
              ('aback', 1),
              ('abandon', 0),
              ('abdu', 0),
              ('abel', 0),
              ('abil', 0),
              ('abl', 0),
              ('abroad', 0),
              ('absenc', 0),
              ('absente', 0),
              ('absolut', 0),
              ('abstain', 0),
              ('abstent', 0),
              ('absurd', 1),
              ('academi', 0),
              ('accept', 0),
              ('access', 0),
              ('accid', 0),
              ('acclaim', 0),
              ('accommod', 0),
              ('accompani', 0),
              ('accomplish', 0),
              ('accord', 1),
              ('accordingli', 0),
              ('account', 0),
              ('accru', 0),
              ('accur', 0),
              ('accus', 1),
              ('ace', 0),
              ('achiev', 0),
              ('acknowledg', 0),
              ('acosta', 0),
              ('acquir', 0),
              ('across', 0),
      

In [27]:
doc_dictionary

OrderedDict([('aaron', 0),
             ('aback', 0),
             ('abandon', 0),
             ('abdu', 0),
             ('abel', 0),
             ('abil', 0),
             ('abl', 0),
             ('abroad', 0),
             ('absenc', 0),
             ('absente', 0),
             ('absolut', 0),
             ('abstain', 0),
             ('abstent', 0),
             ('absurd', 0),
             ('academi', 0),
             ('accept', 0),
             ('access', 0),
             ('accid', 0),
             ('acclaim', 0),
             ('accommod', 0),
             ('accompani', 0),
             ('accomplish', 0),
             ('accord', 1),
             ('accordingli', 0),
             ('account', 0),
             ('accru', 0),
             ('accur', 0),
             ('accus', 0),
             ('ace', 0),
             ('achiev', 0),
             ('acknowledg', 0),
             ('acosta', 0),
             ('acquir', 0),
             ('across', 1),
             ('act', 1),
             ('

# tf-idf calcluation

### 5. tf-idf를 구한다.

In [21]:
array = list()

for value in doc_dictionary_list[0].values(): # 제일 첫번째 같은 경우 numpy_array_stack에다가 저장한다. 
    array.append(value)

numpy_array_stack = np.array(array) 

for i in range(1, len(doc_dictionary_list)):#1번부터 60번까지 하나씩 numpy_array_stack에 저장한다. 
    array = list()

    for value in doc_dictionary_list[i].values():
        array.append(value)

    numpy_array = np.array(array)
    
    numpy_array_stack = np.vstack((numpy_array_stack, numpy_array))

In [22]:
df = np.sum(numpy_array_stack, axis=0)
N = len(numpy_array_stack)
tf = numpy_array_stack + 1

In [23]:
# tf_idf를 구한다. 
tf_idf = np.log(tf + 1) * np.log(N / df)

# query

### 6. query가 속한 document들만 가져온다. 

In [29]:
with open('query.txt', 'r') as f:
    query = f.readline()

In [30]:
query

'president obama'

In [31]:
query_word = query.split(' ') # query문을 token별로 자른다. 

In [38]:
query_doc_set = set() # 

for word in query_word:
    temp = inverted_index_dic[porter_stemmer.stem(word)]
    print(porter_stemmer.stem(word))
    for doc_index in temp:
        query_doc_set.add(doc_index)

presid
obama


In [33]:
query_doc_set

{6,
 7,
 9,
 14,
 17,
 30,
 36,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59}

In [39]:
print(doc_dictionary_list[6]['obama'], doc_dictionary_list[6]['presid'])

4 2


In [346]:
for index in query_doc_set:
    print(tf_idf[index])

[2.83798339 2.83798339 2.07648338 ... 4.49809725 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 4.8214451  ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83798339]
[2.83798339 2.83798339 2.07648338 ... 2.83798339 2.83798339 2.83